version: "2.1"
services:

  deluge:
    image: "linuxserver/deluge:latest"
    container_name: "deluge"
    hostname: "deluge"
    restart: "unless-stopped"
    environment:
      PUID: '${PUID}'
      PGID: '${PGID}'
      TZ: '${TZ}'
    volumes:
      - '${CONFIG_DIR}/deluge:/config'
      - '${DOWNLOADS_DIR}:/downloads'
      - '${MEDIA_DIR}:/media'
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
networks:
  default:
    external:
      name: $DOCKER_MY_NETWORK
