version: "2"
services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    restart: unless-stopped
    volumes:
      - postgres:/config
    ports:
      - 8084:8080
volumes:
  postgres:
    driver: local

networks:
  default:
    external:
      name: caddy_net
