version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:nightly
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - '${CONFIG_DIR}/jellyfin:/config'
      - '${MEDIA_DIR}/tvshows:/data/tvshows'
      - '${MEDIA_DIR}/movies:/data/movies'
      - '${MEDIA_DIR}/books:/data/books'
    ports:
      - 8096:8096
    devices:
      - "/dev/dri:/dev/dri"
    restart: unless-stopped
networks:
  default:
    external:
      name: caddy_net
