version: "3.7"
services:

  nzbget:
    image: "linuxserver/nzbget:latest"
    container_name: "nzbget"
    hostname: "nzbget"
    restart: "unless-stopped"
    environment:
      PUID: '${PUID}'
      PGID: '${PGID}'
      TZ: '${TZ}'
    volumes:
      - '${CONFIG_DIR}/nzbget:/config'
      - '${DOWNLOADS_DIR}:/downloads'
      - '${MEDIA_DIR}:/media'

networks:
  default:
    external:
      name: $DOCKER_MY_NETWORK