version: "2.1"
services:

  transmission:
    image: "lscr.io/linuxserver/transmission:latest"
    container_name: "transmission"
    hostname: "transmission"
    restart: "unless-stopped"
    environment:
      PUID: '${PUID}'
      PGID: '${PGID}'
      TZ: '${TZ}'
    volumes:
      - '${CONFIG_DIR}/transmission:/config'
      - '${DOWNLOADS_DIR}:/downloads'
      - '${MEDIA_DIR}:/media'
    ports:
      - 9092:9091
      - 51413:51413
      - 51413:51413/udp
networks:
  default:
    external:
      name: $DOCKER_MY_NETWORK
