version: '2'

services:
   ubooquity:
    restart: always
    image: zerpex/ubooquity-docker
    container_name: ubooquity
    volumes:
      - /home/elightcap/mediaserverv2/caddy/config/ubookuity:/config
      - /mnt/nfs/media:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/New_York
    ports:
      - 2202:2202
      - 2502:2502
networks:
  default:
    external:
      name: caddy_net
